.PHONY: clean All

All:
	@echo "----------Building project:[ Menu_Selection_enhancement - Debug ]----------"
	@cd "Menu_Selection_enhancement" && "$(MAKE)" -f  "Menu_Selection_enhancement.mk"
clean:
	@echo "----------Cleaning project:[ Menu_Selection_enhancement - Debug ]----------"
	@cd "Menu_Selection_enhancement" && "$(MAKE)" -f  "Menu_Selection_enhancement.mk" clean
