.PHONY: clean All

All:
	@echo "----------Building project:[ Cipher_Encryption_OOP - Debug ]----------"
	@cd "Cipher_Encryption" && "$(MAKE)" -f  "Cipher_Encryption_OOP.mk"
clean:
	@echo "----------Cleaning project:[ Cipher_Encryption_OOP - Debug ]----------"
	@cd "Cipher_Encryption" && "$(MAKE)" -f  "Cipher_Encryption_OOP.mk" clean
