.PHONY: clean All

All:
	@echo "----------Building project:[ Registration_and_login - Debug ]----------"
	@cd "Registration_and_login" && "$(MAKE)" -f  "Registration_and_login.mk"
clean:
	@echo "----------Cleaning project:[ Registration_and_login - Debug ]----------"
	@cd "Registration_and_login" && "$(MAKE)" -f  "Registration_and_login.mk" clean
