.PHONY: clean All

All:
	@echo "----------Building project:[ Menu_Selection - Debug ]----------"
	@"$(MAKE)" -f  "Menu_Selection.mk"
clean:
	@echo "----------Cleaning project:[ Menu_Selection - Debug ]----------"
	@"$(MAKE)" -f  "Menu_Selection.mk" clean
